server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/zhaowenqiao/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
# 访问路径 http://localhost:3344/{label}/{application}-{profile}.yml   如:http://localhost:3344/main/application-pro.yml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka