server:
  port: 80

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 入驻地址
  #      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/ # 入驻地址
  instance:
    instance-id: order80
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
#    lease-expiration-duration-in-seconds: 2 # eureka最后一次收到心跳等待的时间
spring:
  application:
    name: cloud-order-service

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.wenqiao.service.UserService: debug

